import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PlaceProvider } from "./context/PlaceContext";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
      <PlaceProvider>{children}</PlaceProvider>
          
          
      
        
      </body>
    </html>
  );
}
