import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PlaceProvider } from "./context/PlaceContext";
import { AuthProvider } from "./context/AuthContext";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AuthProvider>
          <PlaceProvider>
            {children}
          </PlaceProvider>
        </AuthProvider>




      </body>
    </html>
  );
}
